export const FETCH_SERVICES_START = 'FETCH_SERVICES_START'
export const FETCH_SERVICES_SUCCESS = 'FETCH_SERVICES_SUCCESS'
export const FETCH_SERVICE_START = 'FETCH_SERVICE_START'
export const FETCH_SERVICE_SUCCESS = 'FETCH_SERVICE_SUCCESS'